// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempleTours.Models;

namespace TempleTours.Migrations
{
    [DbContext(typeof(ReservationsDbContext))]
    [Migration("20210317221504_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TempleTours.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupSize")
                        .HasColumnType("int");

                    b.Property<int?>("TimeTourSlotID")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("TimeTourSlotID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TempleTours.Models.TourSlot", b =>
                {
                    b.Property<int>("TourSlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeInfo")
                        .HasColumnType("datetime2");

                    b.HasKey("TourSlotID");

                    b.ToTable("TourSlots");
                });

            modelBuilder.Entity("TempleTours.Models.Reservation", b =>
                {
                    b.HasOne("TempleTours.Models.TourSlot", "Time")
                        .WithMany()
                        .HasForeignKey("TimeTourSlotID");

                    b.Navigation("Time");
                });
#pragma warning restore 612, 618
        }
    }
}
